### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by happYT12** [joker-ware/JokerCord#11]
**Describe the bug**
it spam automaticly but not catch pokemons what to do

**To Reproduce**
Steps to reproduce the behavior

**Screenshots**

**Operating system**
8.1 pro

**Comment by joker-ware** [comment]
If you havent, go to the webpage and click on settings>enable/disable guilds, and enable the guilds you want the bot to capture in. Then reboot the bot. All of them come disabled by default for security reasons.

**Comment by joker-ware** [comment]
Has it been solved?

**Comment by happYT12** [comment]
no man i open guild all are enabled plz your discord id

**Comment by joker-ware** [comment]
Can you try to download the app again and try it from scratch? Maybe you missed any setup.

**Comment by happYT12** [comment]
2 hours work fine then but now it say something went wrong with token and token is correct

**Comment by joker-ware** [comment]
Older versions of the app sahow Token Error even when there is not problem with it. Can you show me the entire error message? (If you are going to screenshot it, pleas emake sure to censor the token)
