### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by GoldenAdrien** [joker-ware/JokerCord#12]
Hi i was wondering if there was any way to make it so that the bot wouldn't make the first letter of the pokemon name uppercase

**Comment by joker-ware** [comment]
Do you mean when catching? I think that was changed some versions ago. If you mean on the Custom List, I am looking forward to change that.

**Comment by joker-ware** [comment]
My bad... I just thought I had changed that. Now it is fixed. You can download bot_thread.py

**Comment by GoldenAdrien** [comment]
thanks!
