### ISSUE TITLE
[BUG]Windows 10, my guilds.json is empty and when i start localhost:5555 the website doesn't register any channels

### ISSUE THREAD

**Issue by DeathIsDead** [joker-ware/JokerCord#13]
my guilds.json is empty and when i start localhost:5555 the website doesn't register any channels

**Comment by joker-ware** [comment]
This bug has been seen previously. Is there any other log on the command line?

**Comment by DeathIsDead** [comment]
Let me check

**Comment by DeathIsDead** [comment]
It runs the log like normal, but there isn't any spam happening on my server

**Comment by momo22321** [comment]
Well the spam ( windows) for me happens for and stops for a solid hour.
![Screenshot (3)](https://user-images.githubusercontent.com/60834700/74105035-4c6f8580-4b52-11ea-8e03-31ad748bfbd5.png)

**Comment by momo22321** [comment]
![image](https://user-images.githubusercontent.com/60834700/74105095-c43db000-4b52-11ea-842e-c52f100aa835.png) (FIX) Just stay on discord
