### ISSUE TITLE
[BUG]Extreme lag in catching, Error of some kind, and massive ram usage

### ISSUE THREAD

**Issue by Hoff2567** [joker-ware/JokerCord#14]
I have the delay set to 1 second for the server/guild yet it can still take several minutes and often misses the catch:
![image](https://user-images.githubusercontent.com/25837925/67820095-4287b200-fa8e-11e9-8b23-e249474b9e65.png)

As well after some time simply doesn't attempt to catch anything at all.

----------

I've no idea what this error is and it has stopped showing up once I restarted joker.py completely and am unable to reproduce it.

![image](https://user-images.githubusercontent.com/25837925/67820151-7bc02200-fa8e-11e9-8197-e8e1a7d793d4.png)

-------------

The ram usage gets high extraordinarily quickly when using the spammer built in. I hit about 10gb ram usage on python within a half hour. Without the spammer it still grows infinitely though much more slowly. I've also noticed joker.py takes quite a bit of time before it begins actually running after having been started as well. Usually anywhere from 5-10 minutes and reaching 1.5-2gb of ram.

-----------

All issues were on Windows 7
Python version 3.8.0

**Comment by joker-ware** [comment]
Hello and thanks for trying my bot and for reaching out. First of all, having such a short delay between messages mot only minimizes the efectiveness of the bot, because you can only send like 5 messages between a period of time, it will make you be banned from discord in a very short time. For safety purposes, (supposing you areuusing an alt, which is not that important),. I recommend you to set a delay of not less than 5-6 seconds. If you are still having issues with that delay, contact me again.

**Comment by joker-ware** [comment]
Any update on this? I have been busy lately but I will try to make some time to fix things.

**Comment by tokengold** [comment]
Your work was amazing, so I have to thank you, I made some changes and now it's working perfectly. I wonder if it is possible to make a catch with random delay

**Comment by joker-ware** [comment]
Thank you! Can you please make a brief explanation of what was your problem and how did you solve it? It would be very useful as some users are experiencing problems with json handling. Also, unfortunately there isn't a random delay at this moment, however, it is my intention to add it soon.

**Comment by tokengold** [comment]
I changed the default port 5555, removed and removed spam because it would not use. As other changes were irrelevant, they are personal.
About the delay, I can not find a place to try to add the "random" could give me a light?

**Comment by joker-ware** [comment]
Sure thing!. Just change this on the file bot_thread.py:
![Screenshot_20191113-075024_Firefox](https://user-images.githubusercontent.com/26441684/68740089-8cbe7680-05ea-11ea-9442-a753c2f95aa2.png)

Where it says asyncio.sleep(int.... ) replace the code inside the Parenthesis () to:
`random.randrange(1, MAX)` Where max is an **Integer** of your choice.(0,7,5..). If you only nee. To set the delay for normal catches, replace the code below the `else` statement. If you also wanna affect the legendary catches, copy the same code and put it below the if.

**Comment by tokengold** [comment]
await asyncio.sleep(random.randrange(3, 9))

showed no error but stopped capturing

**Comment by tokengold** [comment]
You're a beast man, really did an amazing job. Your organization in the project also can not be missed;)

**Comment by tokengold** [comment]
no problems until today, the following appeared: Do you know how to solve mr?
![error](https://user-images.githubusercontent.com/57613603/69110215-5ea8be80-0a50-11ea-9f17-ee70dab9f313.png)

**Comment by joker-ware** [comment]
Is it appearing repeatedly?

**Comment by tokengold** [comment]
yes, downloaded again and the same thing happens

**Comment by tokengold** [comment]
I found that only my original account is not working. In my fake account works normally, how do I solve?

**Comment by joker-ware** [comment]
I have no clue. Can you check the token in your preferences? Maybe you copied it incorrectly.

**Comment by tokengold** [comment]
I logged in to discord to see if he was right and entered. See the error that appears:
![kay](https://user-images.githubusercontent.com/57613603/69279898-af88f600-0bbb-11ea-88b4-788f914c6c1d.png)

**Comment by joker-ware** [comment]
I see. It is somehow having trouble when reading messages which contain animated emoji. Can you check that 1- No server has a strange name with emoji or weird characters and see if there have been any animated emoji in any of your servers?

**Comment by tokengold** [comment]
yes there is

**Comment by joker-ware** [comment]
Never mind. It seems like it is a Discord py error. Please open your terminal and type
```bash
pip3 install --upgrade discord.py
```

**Comment by tokengold** [comment]
thanks, started working again

**Comment by tokengold** [comment]
very nice man, how do i donate?

**Comment by joker-ware** [comment]
Aw thank you so much! I really appreciate that :)
You can donate to my PayPal here: paypal.me/jokerware

**Comment by tomioBiju** [comment]
Hello, I would like to start informing that I appreciate very much very much your work.

I have only a small doubt. Can you start multiple tokens? because I would like to start 5 accounts in just one process for spamming messages. if possible, could you tell me how?

**Comment by joker-ware** [comment]
Hello, it is not possible only with one process, but you can download the bot several times and configure each one. There shouldn't be any problem with that

**Comment by tomioBiju** [comment]
I see, searched for spam only projects for hours, but found nothing. Even so, i appreciate your response.

**Comment by joker-ware** [comment]
Can you elaborate a bit more on how you filled the preferences page? What are the errors showing?

**Comment by tomioBiju** [comment]
have no errors, I was just wanting to add more than one account to a single project

**Comment by joker-ware** [comment]
If the reason is for multi spamming, the next version will provide that. Already have completed it I just have to release the update.

**Comment by tomioBiju** [comment]
that was exactly what I needed. thank you for the information

**Comment by joker-ware** [comment]
The update has been released, if you wanna try it.
