### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by screamings1** [joker-ware/JokerCord#15]
**Describe the bug**
Whenever I launch joker, it loads, but later says 
if (message.author.id != client.user.id and ev == 1 and (guild_list[str(message.guild.id)][0] == "True")): #and "A wild" in message.content):
KeyError : (Random numbers)

**To Reproduce**
Steps to reproduce the behavior
All I did was restarted my pc, and when i launched back up, it gave me that problem
**Screenshots**
https://gyazo.com/2b5b6efae8ffbee4a6dc71041a9d27c7

**Operating system**
Windows 10

**Comment by screamings1** [comment]
It starts fine at first with * Serving Flask app "joker" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on

but later gets if (message.author.id != client.user.id and ev == 1 and (guild_list[str(message.guild.id)][0] == "True")): #and "A wild" in message.content):
KeyError :

**Comment by joker-ware** [comment]
Hello and thanks for reaching out. As I have seen before, this error has been happening to some users and I still have to research about it. Can you please see the content of preferences.json and /User/guilds.json and tell me if any of them are empty? (In case of preferences, it has some text written on it, but check if there is text after the :, like on token: it should have a large text). If guild.json is empty while preferences.json is not, please reach out to me and I will try to solve it.

**Comment by clerix589** [comment]
Hi, how are you? If I have the same problem, it stops and a message appears that says: type error argument of type "keyerror" is not iterable. Is there any solution?

**Comment by breadow** [comment]
> Hi, how are you? I have the same problem, it stops and a message appears that says: type error argument of type "keyerror" is not iterable. Is there any solution?

same problem, my guild preference is empty while preferences.json isnt
