### ISSUE TITLE
[Auto Catcher Does Not Work]

### ISSUE THREAD

**Issue by ludwigpaul** [joker-ware/JokerCord#16]
Hi, The auto catcher does not work, but everything else seems to be working properly because I'm not getting any error messages.

**Comment by joker-ware** [comment]
Can you send me a screenshot of your preferences.json ? (Please censor any sensitive info, specially the token)

**Comment by ludwigpaul** [comment]
apparently it worked perfectly after I restarted the bot a couple times. But now I'm having issues with the pokecord itself. Pokecord isn't responding to my commands at all. Am I banned?

**Comment by ludwigpaul** [comment]
I might've gotten in the blacklist? Although I set the auto catcher timer to 8 seconds?

**Comment by joker-ware** [comment]
Yes it is probable. Wait some time to check wether it wasn't a pokecord problem. Also, I hope you were using and alt, were you?

**Comment by cameron4533** [comment]
The problem i had was that the pokemon spawn image was posted in like a miniature version. Worked fine after changing that setting on pokecord
