### ISSUE TITLE
Bot stops running (error) after some minutes

### ISSUE THREAD

**Issue by ImBored321** [joker-ware/JokerCord#17]
![Screenshot_20191119-110155_Termux](https://user-images.githubusercontent.com/58049448/69371567-0106b300-0c98-11ea-8606-599b234f4800.jpg)
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Screenshots**

**Operating system**

**Comment by joker-ware** [comment]
It is a discord.py problem. Just run
```bash
pip3 install --upgrade discord.py
```
