### ISSUE TITLE
Stops Randomly

### ISSUE THREAD

**Issue by OOF-RIF** [joker-ware/JokerCord#18]
Okay so I want to have the bot run overnight and allow me to catch basically everything. But for some reason it just stops. Then when I go back to my computer it just reboots. It says that is is doing something but it does not. I also get this message; "127.0.0.1 - - [22/Nov/2019 08:22:07] code 400, messag" HTTPStatus.BAD_REQUEST -N\x00\x00\x00\x01\x00\x00\x04\x00\x1b\x00\x00\x00M')" like every 5 seconds I don't know why but if you could help that would be great.

**Comment by joker-ware** [comment]
Just to check, are you using httpS instead of http?

**Comment by OOF-RIF** [comment]
Im not sure. How could I check.

**Comment by joker-ware** [comment]
Check the link of the JokerCord webpage

**Comment by OOF-RIF** [comment]
It is http

**Comment by Hatchochwia** [comment]
i got the same problem man it used to work fine i got tons of pokemons now it works for coupel if min then it just stops spaming and catching both
