### ISSUE TITLE
Auto Catcher doesn't work

### ISSUE THREAD

**Issue by cameron4533** [joker-ware/JokerCord#19]
**Describe the bug**
Auto catcher doesn't work.. auto spam does.

**To Reproduce**
Idk
**Screenshots**

**Operating system**
Windows 10

**Comment by joker-ware** [comment]
Any error log in the console?

**Comment by cameron4533** [comment]
everything in the console is fine

**Comment by kairanaquazi** [comment]
Same thing happens to me

**Comment by kairanaquazi** [comment]
It doesn't appear you have all the assets for the pokemon skins

**Comment by kairanaquazi** [comment]
That seems to be the issue

**Comment by kairanaquazi** [comment]
never mind

**Comment by kairanaquazi** [comment]
oof. I forgot to enable

**Comment by cameron4533** [comment]
does yours work?

**Comment by kairanaquazi** [comment]
yes

**Comment by cameron4533** [comment]
do you have discord? just want something to communicate quicker.

**Comment by kairanaquazi** [comment]
you need to go to "localhost:5555" then hit settings then hit the button that says "enable/disable guilds" then enable yours.

**Comment by cameron4533** [comment]
i've everything setup right. it just doesn't do anything

**Comment by kairanaquazi** [comment]
try refreshing your bot. theres a link in the site

**Comment by cameron4533** [comment]
did multiple times, still nothing. I've reinstalled the whole file, reinstalled the required libraries, i don't know whats wrong with it.

**Comment by kairanaquazi** [comment]
im lost

**Comment by kairanaquazi** [comment]
screenshots would really help

**Comment by cameron4533** [comment]
of what

**Comment by cameron4533** [comment]
![JOKERCORD](https://user-images.githubusercontent.com/58092705/69491712-6e644080-0e5e-11ea-8f3a-3e2aaafb558b.png)

**Comment by kairanaquazi** [comment]
of the site

**Comment by kairanaquazi** [comment]
sorry i could be more specific

**Comment by kairanaquazi** [comment]
its like 120AM for me

**Comment by kairanaquazi** [comment]
Late night coding

**Comment by kairanaquazi** [comment]
you can also DM me on discord - thepronoobkq#3751

**Comment by cameron4533** [comment]
sent friend req

**Comment by kairanaquazi** [comment]
k
