### ISSUE TITLE
Switch prefix

### ISSUE THREAD

**Issue by kairanaquazi** [joker-ware/JokerCord#20]
I am using the bot in two different servers, one of them has p! as Pokecord's prefix, the other has ? as the prefix. I can't use the auto-catcher in the second because it says "p!catch..." when it should say "?catch". Is there a way to fix this?

**Comment by joker-ware** [comment]
Sorry but there is no current way to change the prefix. It is in my todo list but I have been incredibly busy lately. Hope to add it soon.

**Comment by konyalisafa** [comment]
you can change line 166 and 170 in bot_thread.py, that should work right?

**Comment by joker-ware** [comment]
Yep

**Comment by kairanaquazi** [comment]
I added a prefix area in the preferences and changed the code to match the guild id with the dictionary and use that prefix.
