### ISSUE TITLE
Login Failure is not etirable 

### ISSUE THREAD

**Issue by Lime-Sky** [joker-ware/JokerCord#21]
After I reboot the bot,It always can changed setting that I saved

**Comment by joker-ware** [comment]
Sorry, I don't understand your question. Can you elaborate it?

**Comment by Lime-Sky** [comment]
![dfdfgdgf](https://user-images.githubusercontent.com/56623323/70487856-409f1d00-1b29-11ea-8989-61ca09413ae5.JPG)

**Comment by joker-ware** [comment]
Seems like you typed in the wrong token. Are you sure you are not using a BOT token?

**Comment by ManiacMana** [comment]
Same thing happend to me, but happend on first time loading. Any fix yet?

**Comment by joker-ware** [comment]
Check your token, make sure it is a Bot token. If it persists,message again

**Comment by Lime-Sky** [comment]
Its works now,Thanks,I just need to restart the bot
