### ISSUE TITLE
Commands in terminal

### ISSUE THREAD

**Issue by Rebisoft** [joker-ware/JokerCord#22]
sudo apt-get command not found and unable to run to path folder. i saw the vid and tried using fish but still cldnt do sudo apt-get so i used homebrew to install but got stuck at the "run JokerCord navigate to the downloaded folder" command 

Please make a more concise guide.Apparently macOS 10.8 and further are unable to use sudo apt-get

**Comment by joker-ware** [comment]
Sorry, that is my fault. I haven't still updated the Mac os part of the tutorial. Apt get is only for Linux, you should use ```brew``` instead. Can you tell me here did you get stuck? What do you need to install now?

**Comment by Rebisoft** [comment]
I am not sure myself. I used brew until the path to folder part. From there it just can't find the path

**Comment by joker-ware** [comment]
What path ?

**Comment by Rebisoft** [comment]
The 4th step for the Linux/MacOSX guide

**Comment by joker-ware** [comment]
Have you seen the tutorial video?I think I explain it there

**Comment by Rebisoft** [comment]
![Screenshot 2019-12-19 at 6 20 38 PM](https://user-images.githubusercontent.com/58822137/71165715-52509500-228c-11ea-8260-8643287132ff.png)
i get this after doing the python3 joker.py command. do i just go to the browser thing or is this not supposed to happen?

**Comment by joker-ware** [comment]
You wrote a wrong token. Please check if you wrote an user token , not a BOT token.

**Comment by Rebisoft** [comment]
uhhh where do i get a user token

**Comment by joker-ware** [comment]
It's in the tutorial.

**Comment by Rebisoft** [comment]
oh ok thanks for your patience

**Comment by Rebisoft** [comment]
there's no "tools" menu for me when i open the discord tab
