### ISSUE TITLE
[BUG] When I try to make the bot run, the preferences erase, the servers where I am don't appear, that kind of things.

### ISSUE THREAD

**Issue by Aresgamer57** [joker-ware/JokerCord#23]
![image](https://user-images.githubusercontent.com/37967909/70857874-cece2700-1ecc-11ea-8bcd-2d4f02ba541c.png)

**Comment by joker-ware** [comment]
There seems to be a problem when Windows tries to write to the Json... I still haven't found a solution. Can you try running the program as administrator?
