### ISSUE TITLE
@joker-ware, you should make it so that the "spam intervals" can reach to decimals and the lowest is not 1.

### ISSUE THREAD

**Issue by ExtremSnek** [joker-ware/JokerCord#25]
Please make "spam interval" go lower than 1 second. @joker-ware 
![test](https://user-images.githubusercontent.com/58981851/70999410-7c3f7580-212d-11ea-97ac-1583992a9d7d.PNG)

Hope you reply soon!

**Comment by joker-ware** [comment]
Sorry, I can't make it go lower than that for security reasons. Any number below 5 is risky enough, and with delays lower than 1 your account will be banned in less than 2 days

**Comment by ExtremSnek** [comment]
> Sorry, I can't make it go lower than that for security reasons. Any number below 5 is risky enough, and with delays lower than 1 your account will be banned in less than 2 days

I seee... Well, thank you for replying and I hope you make greater improvements in the future! 😃 Good luck!  ~ snek

**Comment by triple7inc** [comment]
Let's protect it way more by adding a range of delay to apply for every action in the settings. Such as 1 to 3, whereof it is way much more random.
