### ISSUE TITLE
[BUG] None of my servers are showing up in servers that im in

### ISSUE THREAD

**Issue by OofyBoi** [joker-ware/JokerCord#27]
No servers are showing up in the list.

Here is a screenshot
![Captureyee](https://user-images.githubusercontent.com/46251775/71127651-7becbc00-21b9-11ea-97b5-8f3c2ad29dc8.PNG)
 
Oh yeah I'm on windows

**Comment by OofyBoi** [comment]
Also, every single time I run it, errors pop up on the command prompt

**Comment by joker-ware** [comment]
Fixed on last version

**Comment by OofyBoi** [comment]
You replied so many months later that I'm already banned on pokecord.

**Comment by joker-ware** [comment]
Sorry, hadn't have time to fix the problem and it was yesterday that I found a solution
