### ISSUE TITLE
[BUG]localhost refused to connect.

### ISSUE THREAD

**Issue by TRITONLATAM** [joker-ware/JokerCord#29]
**Describe the bug**
when you entered localhost it automatically disconnects

**Screenshots**
![image](https://user-images.githubusercontent.com/59143037/71327431-19602c80-24e7-11ea-8cc4-b678533ec3ca.png)

**Operating system**

**Comment by TRITONLATAM** [comment]
pls help me

**Comment by joker-ware** [comment]
Can you show me the console log? Please censor your token

**Comment by TRITONLATAM** [comment]
How can I do that, excuse me, I'm a newbie in this :(

**Comment by TRITONLATAM** [comment]
bro now only the auto catch is working but not the auto-spam

**Comment by TRITONLATAM** [comment]
can you help me pls? :(

**Comment by joker-ware** [comment]
Sorry for the delay, I am a bit busy. Just go to the homepage and click the edit configuration button, then type the channel Id where you want to spam to. Toy can check the video I made for a bit of guidance

**Comment by TRITONLATAM** [comment]
thx bro but I'm afraid that when you restart the bot it will close again

**Comment by joker-ware** [comment]
It won't, as long as you don't modify the token or something

**Comment by TRITONLATAM** [comment]
Bro restarted it and it closed :(

**Comment by joker-ware** [comment]
No log in the console?

**Comment by TRITONLATAM** [comment]
I didn't understand :) what do I have to do

**Comment by joker-ware** [comment]
Sorry I will help you another day, I'm too tired and need to sleep :(

**Comment by TRITONLATAM** [comment]
ok bro :D thx

**Comment by TRITONLATAM** [comment]
hi bro! :D

**Comment by TRITONLATAM** [comment]
can you help me?
