### ISSUE TITLE
[BUG] Python 3.8 updates for async calls

### ISSUE THREAD

**Issue by triple7inc** [joker-ware/JokerCord#31]
**Describe the bug**
joker.py:26: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  async def startClient():
**To Reproduce**
Steps to reproduce the behavior
Run Python 3.8.x (newest version)

**Screenshots**

**Operating system**
Windows Server 2019

**Comment by joker-ware** [comment]
It seems like a Python 3.8 problem. Please use versions 3.6-3.7 instead.

**Comment by triple7inc** [comment]
It does works, just the regular warning messages.
