### ISSUE TITLE
[FEATURE] Add custom prefixes

### ISSUE THREAD

**Issue by mandar1jn** [joker-ware/JokerCord#37]
Can you please add support for custom prefixes because most servers don't use p! but .

**Comment by joker-ware** [comment]
Hello, sorry for the inconvenience. For now there isn't a simple way to do so, but you can edit these lines as a temporary solution:
![Screenshot_20200102-180927_Firefox](https://user-images.githubusercontent.com/26441684/71680742-31f40080-2d8b-11ea-8c1a-f92102d80486.png)

**Comment by joker-ware** [comment]
This will be added in next update.
