### ISSUE TITLE
LOGIN FALIURE NOT ITERABLE

### ISSUE THREAD

**Issue by zanmeinin7** [joker-ware/JokerCord#38]
**Describe the bug**
Login Faliure Is Not Iterable

**To Reproduce**
Steps to reproduce the behavior

**Screenshots**
![Screenshot_9](https://user-images.githubusercontent.com/58526129/71771253-36244780-2f5e-11ea-9e13-1605181cdfb6.png)

**Operating system**
(url)

**Comment by joker-ware** [comment]
Improper token passed. Check the token again and check if it is an USER token not a BOT token

**Comment by zanmeinin7** [comment]
how do i do that?

**Comment by joker-ware** [comment]
There is a tutorial on how to get a token on the Readme.

**Comment by zanmeinin7** [comment]
im sorry for so many questions, what do we do after geting token?

**Comment by joker-ware** [comment]
Go to the not webpage and enter all the credentials again as the first time

**Comment by FerretShiny** [comment]
so once i get the token. go to localhost:5555 and go to edit preferences, then put my token in, then reboot?
because i got the same issue

**Comment by joker-ware** [comment]
Yes.

**Comment by joker-ware** [comment]
Issue fixed in latest version.

**Comment by FerretShiny** [comment]
Yay, thank you
