### ISSUE TITLE
[BUG]TypeError: argument of type 'ClientConnectorError' is not iterable

### ISSUE THREAD

**Issue by Sylveontrainer** [joker-ware/JokerCord#39]
**Describe the bug**
The bot starts fine and even starts spamming too, but just after few seconds this error shows up. If token was the problem it wouldn't even spam. 

**Screenshots**
![Annotation 2020-01-07 011731](https://user-images.githubusercontent.com/59578685/71842300-85e44980-30eb-11ea-8d06-dcc904cb66c7.png)

**Operating system**
Windows 10 pro

Please look into and suggest me what can I do. Thanks .

**Comment by joker-ware** [comment]
This should be fixed in the last version.
