### ISSUE TITLE
Something wrong with channel id[BUG]

### ISSUE THREAD

**Issue by quangkhai098** [joker-ware/JokerCord#41]
![Capture](https://user-images.githubusercontent.com/59795412/72219170-a0984180-3575-11ea-831f-d46c5edaecb0.PNG)

I have check my channel and user token over and over again but i always receive these errors

**Comment by joker-ware** [comment]
Something's wrong with the token. It is a common error to use a bot token instead of an user token. Please confirm if this is the case
