### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by happyyt1** [joker-ware/JokerCord#42]
**Describe the bug**
file do not have a program associated with it for performing this action .please install a programif already installled create an asscoition etc

**To Reproduce**
Steps to reproduce the behavior

**Screenshots**

**Operating system**
8.1 pro windows
i have done python add to path and indtalled flask

**Comment by riesz01** [comment]
have you add the path?

**Comment by happyyt1** [comment]
> have you add the path?

yes

**Comment by joker-ware** [comment]
Hello, have you tried running the bot from the console?
