### ISSUE TITLE
Unable to view Guilds after filling up Token and Channel ID in Preferences[BUG]

### ISSUE THREAD

**Issue by justanotherdumbuser** [joker-ware/JokerCord#45]
Hi I am unable to view the Guilds page even after rebooting once the Preferences page has been filled up. Is there a quick fix for this?
![Screenshot_190](https://user-images.githubusercontent.com/60252983/73053119-dd433180-3ec1-11ea-85d6-2b9d2cf92705.png)

**Comment by joker-ware** [comment]
Please try running the bot as admin of you are in windows. Let me know if that fixes it

**Comment by ImNotFreddy** [comment]
Having a problem like this as well except i also can't see anything except the tokens section in preferences. I am in mac so cant run as admin

**Comment by joker-ware** [comment]
Fixed on last update
