### ISSUE TITLE
JC closes itself

### ISSUE THREAD

**Issue by Raremcman** [joker-ware/JokerCord#48]
I installed the latest versions of python opened up cmd imputed the command and it went through successfully but when I open joker.py it closes before I can do anything, did anyone else have this problem? I need to know what to do next, I used to use this and it worked just fine, but now somethings wrong.

**Comment by joker-ware** [comment]
did you install all required libraries?

**Comment by joker-ware** [comment]
May be fixed on last update

**Comment by ryanMD3084** [comment]
I have the same issue ,  it closes itself immediately after opening. I have done a clean uninstall and re-install and it still does the same.
