### ISSUE TITLE
Connecting very slowly

### ISSUE THREAD

**Issue by donkeysxd** [joker-ware/JokerCord#53]
Hey! I really, really love the bot. It's been working great until recently :(
Whenever I open the bot it takes very long to connect, it used to connect instantly. My main account that does all the catching just doesn't connect at all. It does catch a few spawns here and there but it doesn't spam and skips a lot of spawns. Yes, I downloaded the latest version but I'm still having the same issue!

Thank you c:

**Comment by joker-ware** [comment]
Hello!! Are you using your main account for this? I totally do not recommend that as the risk of ban is very present. Please use an alt . if the account that you are using is in a lot of servers (with a lot of channels) it may be slow (please notice that if you enable spam for a lot of channels the bot starts a thread for each of them so it can be very RAM consuming)

**Comment by donkeysxd** [comment]
> Hello!! Are you using your main account for this? I totally do not recommend that as the risk of ban is very present. Please use an alt . if the account that you are using is in a lot of servers (with a lot of channels) it may be slow (please notice that if you enable spam for a lot of channels the bot starts a thread for each of them so it can be very RAM consuming)

Oh yeah I am using an alt, but this alt is what does the catching for me and is only spamming in 1 channel.

**Comment by joker-ware** [comment]
Fixed on last update
