### ISSUE TITLE
"No Module Named Flask" error or MacOS [BUG]

### ISSUE THREAD

**Issue by arghiz** [joker-ware/JokerCord#54]
**Describe the bug**
I just downloaded the latest version today, 08 Feb 2020.
Currently my OS is Mojave. I cannot proceed because I got this error.

`Traceback (most recent call last):
  File "joker.py", line 1, in <module>
    from flask import Flask, render_template, request, url_for, redirect, flash
ModuleNotFoundError: No module named 'flask'
`

**To Reproduce**
I followed the video tutorial for MacOs.
1.  I went to directory where "JokerCord-master" is.
2. Opened terminal and sd the path.
3. I entered "python3 joker.py"
It gave me the error.

**Screenshots**

**Operating system**
MacOS Mojave.

**Comment by joker-ware** [comment]
You need to install the python libraries. Please paste the command that is in the readme ```pip3 install discord.py flask PIL```
After that it should work. I guess I should've covered the python installation on that video too. For any further question the other linux video covers the full setup (it's practically the same for Mac except for the python installation)

**Comment by arghiz** [comment]
Hi Sir.

I dont know if I have to open the new ticket or not. I'm still having problem after installing the Joker.py.

It gave me this error at the end of the terminal message:

`Cannot connect to host discordapp.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]`

I ignored the message.

Right now I'm at this url.
http://127.0.0.1:5555/setup
When I was going to set the Token and other details, it gave me error.

`Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. `

Any idea how to solve this? Thank you for the software!

**Comment by joker-ware** [comment]
Hi again, this is a known bug with Mac systems, the SSL certificates that come by default with Mac's python are outdated. Just go to Applications/Python3.6/ and double click on ```install.certificates ```.

**Comment by arghiz** [comment]
Hi Sir,
Now the certification solved.

The next hurdle is the Settings page where the Token must be set.
Is there any hardcode to put this setting into the script file?

**Comment by joker-ware** [comment]
Yes, there is. But you wouldn't want to do this, the error doesn't seem right.
Can you run it with ```python3 joker.py runserver -d``` and send any errors?

**Comment by arghiz** [comment]
Hi Sir,

This is the error that I got:

`Corals-MacBook-Pro:JokerCord-master coral$ python3 joker.py runserver -d
joker.py:26: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  async def startClient():
'token'
 * Serving Flask app "joker" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5555/ (Press CTRL+C to quit)

`

Any Idea?

**Comment by joker-ware** [comment]
Can you try adding your token in the webpage ? Don't close that program, run it there

**Comment by arghiz** [comment]
I already run it with that error.
I didnt close the terminal and when I open the url http://127.0.0.1:5555/setup
It still gave me the same error.

`Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. `

When I check back the terminal, it gave me this error:

`[2020-02-08 04:38:05,350] ERROR in app: Exception on /setup [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "joker.py", line 182, in setup
    if(pref["token"] != ""):
KeyError: 'token'
127.0.0.1 - - [08/Feb/2020 04:38:05] "GET /setup HTTP/1.1" 500 -

`

Is that an error or not? What am I should I next?

**Comment by joker-ware** [comment]
Can you check the file preferences.json and see if your token is inside the " " after token:? If not, you can add it there manually as a workaround.

**Comment by arghiz** [comment]
Hi Sir,

I'm sorry I did change the token there.
I have set it back to "token" and the page works fine.

Now when I open the Settings page, it only show 1 text-field. TOKEN.
It's different than the tutorial where it showed 4 fields.

I keyed in the token and reboot the system. But when I clicked on reboot (everytime I clicked on reboot) it gave me this error:

```
This site can’t be reached
127.0.0.1 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```


Did I do it right?

**Comment by joker-ware** [comment]
The only field that should appear is "token". The other ones were removed in the update after I made that video. And yes, that message should appear, because when you click reboot you reboot the bot and the webpage. Please do not press F5 or refresh, instead type the URL directly in the search bar or instead it will reboot for ever.

**Comment by arghiz** [comment]
Hey It works now!

Is there any way to put words instead of random numbers as spam text?

Thank you for the help. I will donate later soon. Thanks!

**Comment by joker-ware** [comment]
Thanks a lot! Sadly no, the option to change the text was removed, but you can modify it yourself in bot_thread.py and changing (inside the spamThread function) where it says ```channelInstance.send() replace the contents inside the parentheses with the text you want (remember to put the text inside quotes like this : "this is an example test"
