### ISSUE TITLE
If Running Multiple Bot Questions [BUG]

### ISSUE THREAD

**Issue by arghiz** [joker-ware/JokerCord#56]
**Describe the problem**
Hi Sir,

Before I do, Is it possible to run multiple bot for different discord server at the same time?

I'm thinking to duplicate **JokerCord-master** folder. Running Joker.py from 2 different terminal at the same time.

But the question is, how to access the bot setting if both of them using the same address _**127.0.0.1:5555**_ ?

**Operating system**
MacOs Mojave.

**Comment by joker-ware** [comment]
Hello, just open the file ```joker.py``` with your favorite text editor, and scroll to the very bottom of the file. Locate the word that says "port" and change the number 5555 to whatever you want (just make sure it doesn't conflict with other ports, don't make it too low neither higher than 65000)

**Comment by arghiz** [comment]
Hey it works very well! Thanks!
