### ISSUE TITLE
Make Catch Time Random (range) [Questions]

### ISSUE THREAD

**Issue by arghiz** [joker-ware/JokerCord#59]
**Describe the problem**
Catching the pokemon in fixed delay second might be a bit suspicious for Pokecord.
How/Is there a way to make the catching delay time random within a certain range number?
For e.g: between 3-30seconds.

Is there a way to hardcode it?

**Operating system**
MacOS.

**Comment by joker-ware** [comment]
Hello, yes you can hardcode it. Just change the line selected on the image (inside bot_thread.py) to the comment at the right (text in green)
![random](https://user-images.githubusercontent.com/26441684/74108540-b05a7400-4b7b-11ea-8eb5-ae71c919255b.png)

**Comment by arghiz** [comment]
Wow it works very well! Thanks. Now less likely I will get banned lol
