### ISSUE TITLE
Bot dont connect

### ISSUE THREAD

**Issue by Reshiramboy** [joker-ware/JokerCord#6]
Hi, i have this problem: the bot of the token no connect in my server

my config is:
{"hash_type": "phash", "local": "False", "token": "CENSORED", "auto_spam": "True", "auto_spam_channel": "spam-poke", "auto_spam_text": "xd", "auto_spam_interval": "1", "custom_list": "True"}

what happen? :(

![image](https://user-images.githubusercontent.com/56449004/66668926-c4718180-ec2c-11e9-99d8-80952f97121f.png)

**Comment by joker-ware** [comment]
Please do not post your token online or else your account can be controlled by anyone who has it. I've edited your comment to censor it. Take that into account. Also there is no need for you to change those things manually, just go to your browser and type http://localhost:5555 , the click Preferences and add your token there. Your spam channel is not the channel name, instead the chhanel id, which you can get following my tutorial on the readme. Lastly, please **RESTART** the bot after changing the token, or else it will not update.

**Comment by joker-ware** [comment]
Please update me with your status. Is it working now?

**Comment by Reshiramboy** [comment]
Sorry, I thought you had to put the token of a bot and it was my own token ... now it works ... but it doesn't capture anything :/ he ignores all the pokemon
![Sin título](https://user-images.githubusercontent.com/56449004/66671044-96427080-ec31-11e9-898a-d90de7f59ada.png)

**Comment by joker-ware** [comment]
Go to the webpage and go to settings> Enable/disable guilds and enable the guild that you want the bot to catch on. Then reboot

**Comment by joker-ware** [comment]
I just updated that in the readme some minutes ago, sorry for that

**Comment by Reshiramboy** [comment]
You're the fucking boss, it works ... thank you very much for your application ♥

**Comment by joker-ware** [comment]
Yes, haha! Glad to hear that. If you don't mind, could you star the project? Just go to the main page and click on the star on the top, that helps me a lot :) Thank you

**Comment by Reshiramboy** [comment]
ok :D

**Comment by joker-ware** [comment]
Thanks ^^
