### ISSUE TITLE
Setting Custom Prefix 

### ISSUE THREAD

**Issue by BluestGarbage** [joker-ware/JokerCord#62]
So I'm attempting to load up bot_thread.py to modify the code for a custom prefix, but the file instantly crashes and no code shows up, what caused this?

**Comment by getbah** [comment]
works fine for me, if i modify bot_thread.py

**Comment by joker-ware** [comment]
Sorry, should be fixed, I was missing a ()

**Comment by arghiz** [comment]
> So I'm attempting to load up bot_thread.py to modify the code for a custom prefix, but the file instantly crashes and no code shows up, what caused this?

Please refer to this step. I tried and works for me.
