### ISSUE TITLE
[BUG] Custom list doesnt works for legendary pokemons

### ISSUE THREAD

**Issue by Supremeaccess** [joker-ware/JokerCord#8]
I have a custom list with all the legendary pokemons, but literally 5 seconds ago a cosmoem spawned and the bot didnt catch it. I check the cmd and it says this "NameError: name 'custom_list' is not defined". In the txt the custom list says "True". What happend?

**Comment by joker-ware** [comment]
Thanks for commenting. Should have been fixed now. Just replace bot_thread.py with the new one.

**Comment by joker-ware** [comment]
Just download everything, if you want. Somehow I managed to push the last update incorrectly so custom delays werent showing.

**Comment by joker-ware** [comment]
Is it now working properly?

**Comment by Supremeaccess** [comment]
I don't know. I have to wait for the next legendary pokemon.

**Comment by joker-ware** [comment]
If no message has shown until now, (if Pokemons have appeared), that probably means it's working. But it would be nice if you confirmed :)

**Comment by joker-ware** [comment]
Also, sorry for the Cosmoem loss, I may have deleted something by accident 😖

**Comment by Supremeaccess** [comment]
I should add normal pokemons to the list to see if it works, but I don't feel like XD. And there is no problem about the cosmoem.

**Comment by Supremeaccess** [comment]
A few moments ago a reshiram appeared and the bot caught it automatically. Custom list works.

**Comment by joker-ware** [comment]
Glad to hear that. Just a quick reminder, I don't know why but not everybody reads all of the readme haha. Just saying if you like my work and the app it would be a great help if you left a star on the top of the main page. That promotes my work a bit, and makes me continue working on it :)
